### ISSUE TITLE
Why this package also named as Wannier19?

### ISSUE THREAD

**Issue by hongyi-zhao** [stepan-tsirkin/wannier-berri#19]
Dear Dr. 

You said that this package is also named as (a.k.a. Wannier19). Any hints for this name?

Regards,
HY

**Comment by stepan-tsirkin** [comment]
Hi, 

it is just the first name of the package, with it I  presented it on a couple of conferences and used in https://www.nature.com/articles/s41535-019-0207-7

The name refers to the creation year 2019, and to  wannier90.

Later it was renamed to a more distinctive name WannierBerri.

wannier19 is still available from pypi, but it is too old and not recommended  to use. 
The old github link https://github.com/stepan-tsirkin/wannier19  still works and redirects to the present repository.

Regards
Stepan.

**Comment by hongyi-zhao** [comment]
> Hi,
> 
> it is just the first name of the package, with it I presented it on a couple of conferences and used in https://www.nature.com/articles/s41535-019-0207-7
> 
> The name refers to the creation year 2019, and to wannier90.

BTW, the 90 in *wannier90* refers to *FORTRAN 90*, instead of the number corresponding to its initial release year.

> 
> Later it was renamed to a more distinctive name WannierBerri.
> 
> wannier19 is still available from pypi, but it is too old and not recommended to use.
> The old github link https://github.com/stepan-tsirkin/wannier19 still works and redirects to the present repository.

Does GitHub also offer this redirection service free of charge?

Regards
HY

**Comment by stepan-tsirkin** [comment]
Yes, I am aware that it is from Fortran90. It actually was intentionally confusing, speaking "ninety" and "nineteen".
Yes, a user may rename any repository, and the old link will redirect to the new one, until the user creates another repo with the old name.
