### ISSUE TITLE
How to fix the error of {TypeError: tabulate() got an unexpected keyword argument 'fout_name'}

### ISSUE THREAD

**Issue by Secondlalala** [stepan-tsirkin/wannier-berri#20]
Dear stepan-tsirkin 
   Hello, i am the user of wannier-berri software, this program helps me a lot in calcualting berry curvature and anomalous Hall conductivity. However, when i am using this software to generate berry curvature. 
![image](https://user-images.githubusercontent.com/44155131/100194341-7ef73d00-2f30-11eb-8c8f-b559f06a2cb9.png)
I find this error:
![image](https://user-images.githubusercontent.com/44155131/100194391-959d9400-2f30-11eb-936e-a0fb29e0a508.png)
this error seems irrelative to the version of python, because i have run this program in both python3.6 and python3.8, but the error remains.
It would be very thankful if you can give me some adivese to solve this error.

**Comment by bbradlyn** [comment]
It looks like the keyword "fout_name" in tabulate was changed to "frmsf_name." Additionally, In line 211 of __main.py, there is a lingering reference to "fout_name" that I think should be changed to "frmsf_name." Changing these two things fixed the issue for me on my local install

**Comment by stepan-tsirkin** [comment]
Hi, 

Dear @Secondlalala , I am happy to know that my code is useful to you, I will be even more happy to know your real name and affiliation, 

Thank you Barry @bbradlyn , really the parameter name changed, and there was a bug. I will update documentation soon.  The bug is fixed in version 0.7.4.1 . 

The idea actually was not to write anything during  the call to the tabulate function (and hence not to use this parameter), because the frmsf file is formatted, and hence huge and  slow to read/write . Instead, an object is returned, which contains all needed data. This object can be pickled for future, and needed data may be written in a convenient form. (The list of output formats will be eventually extended) or raw data may be extracted for further processing. 

A working example is given below. Please, let me know if more bugs appear. 

Regards,
Stepan.

```python
#!/usr/bin/env python3
import os
os.environ['OPENBLAS_NUM_THREADS'] = '1' 
os.environ['MKL_NUM_THREADS'] = '1'

num_proc=4

import pickle
import wannierberri as wberri
import numpy as np

Ef0=5.9325

system=wberri.System_w90('Te',spin=True,berry=True) 
grid=wberri.Grid(system,NKFFT=(18,18,8),length=50)  
tab_result=wberri.tabulate(system,
             grid=grid,
             quantities=["spin","berry"],
             numproc=num_proc)
pickle.dump(tab_result,open("Te_spin_berry_tab.pickle","wb"))

#you may load it in another script
#tab_result=pickle.load(open("Te_spin_berry_tab_len=100.pickle","rb"))

#get the files for fermi surface
tab_result.fermiSurfer(quantity='spin',component='z',efermi=Ef0,npar=num_proc,iband=[18,19],frmsf_name="Te-spin-z-conduction")
# or equivalently
open("Te-spin-z-conduction-2.frmsf","w").write(tab_result.fermiSurfer(quantity='spin',component='z',efermi=Ef0,npar=num_proc,iband=[18,19]))

tab_result.fermiSurfer(quantity='berry',component='x',efermi=Ef0,npar=num_proc,iband=17,frmsf_name="Te-berry-x-valece-top.frmsf") #iband - counts from zero
tab_result.fermiSurfer(efermi=Ef0,npar=num_proc,frmsf_name="Te-E.frmsf")

#or get the data to process in any other way:
recip_lattice=tab_result.recip_lattice
grid=tab_result.grid
Energy_VB=tab_result.get_data(iband=17,quantity='E')
Energy_CB=tab_result.get_data(iband=18,quantity='E')
berry=tab_result.get_data(iband=18,quantity='berry',component='z')
spin=tab_result.get_data(iband=18,quantity='spin')  # all xyz components

# e.g. the H point is :
print (Energy_VB[grid[0]//3,grid[1]//3,grid[2]//2])
# the gap is:
Hpoint=(grid[0]//3,grid[1]//3,grid[2]//2)
print ("The gap at H-point is ",Energy_CB[Hpoint]-Energy_VB[Hpoint])
print(grid,Energy_CB.shape,berry.shape,spin.shape)

```

**Comment by Secondlalala** [comment]
Thank you @stepan-tsirkin  and @bbradlyn , i am a student in South China University of Technology. i am grateful for your respond.  The version of the code i just installed via pip3 is 0.7.3.3. Looking forward to your newly released version of the code.
Regards,
WenQiang Xie

**Comment by stepan-tsirkin** [comment]
Hi WenQiang, 
yesterday I uploaded 0.7.4.1, see: https://pypi.org/project/wannierberri/
try to do `pip install --upgrade wannierberri` again. (Hope that the Great Firewall does not block pip )

Yes, sometimes the new version introduces new bugs. If it happens,please report them, and try to use a previous version before it is fixed. 

Stepan.
